server.port=8081
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/06c17780-fea1-442b-9f82-9c3e5224d664/v2.0
spring.security.oauth2.resourceserver.jwt.audiences=api://e2b91943-82bc-4369-a4c5-151aa20c8f6c,e2b91943-82bc-4369-a4c5-151aa20c8f6c
app.cors.allowed-origins=http://localhost:3000
services.shipments.url=http://localhost:8080
services.catalog.url=http://localhost:8082